export enum Languages {
  ENGLISH = "ENGLISH",
  ITALIAN = "ITALIAN",
  FRENCH = "FRENCH",
  GERMAN = "GERMAN",
  SPANISH = "SPANISH",
  PORTUGUESE = "PORTUGUESE",
}

export enum ActivityTopics {
  BOOKS = "BOOKS",
  MOVIES = "MOVIES",
  SPORTS = "SPORTS",
  CURRENT_AFFAIRS = "CURRENT_AFFAIRS",
  SCIENCE_AND_TECHNOLOGY = "SCIENCE_AND_TECHNOLOGY",
  CULTURE = "CULTURE",
  POLITICS = "POLITICS",
}

export enum ActivityType {
  READING = "READING",
  LISTENING = "LISTENING",
}

export enum ActivityLevel {
  BASIC = "BASIC",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum ActivityStatus {
  PENDING = "PENDING",
  READY = "READY",
}

export enum OutputStatus {
  PENDING = "PENDING",
  READY = "READY",
  REVIEWED = "REVIEWED",
}

export enum ActivityBlockType {
  TEXT = "TEXT",
  AUDIO = "AUDIO",
  OPEN_QUESTION = "OPEN_QUESTION", //
  MULTIPLE_CHOICE_QUESTION = "MULTIPLE_CHOICE_QUESTION",
}
