import { Navbar, Toast } from "@components";
import {
  ThemeProvider,
  AuthProvider,
  TanstackQueryProvider,
  NextAuthProvider,
  useColorTheme,
} from "@contexts";
import { getServerSession } from "next-auth";
import "react-toastify/dist/ReactToastify.css";
import "../styles/global.css";
import StyledJsxRegistry from "../styles/styled-components-registry";
import { ThemedHtml } from "./_themed_html";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const serverSession = await getServerSession();
  console.log({ serverSession });
  return (
    <StyledJsxRegistry>
      <ThemeProvider>
        <ThemedHtml>
          <body suppressHydrationWarning>
            <TanstackQueryProvider>
              <NextAuthProvider session={serverSession}>
                <AuthProvider>
                  <Navbar />
                  {children}
                </AuthProvider>
              </NextAuthProvider>
              <Toast />
            </TanstackQueryProvider>
          </body>
        </ThemedHtml>
      </ThemeProvider>
    </StyledJsxRegistry>
  );
}
