// "use client";
import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Eye,
  EyeOff,
  Pencil,
  PencilLine,
  MessageCircleQuestion,
  Check,
  Mail,
  Trash,
  LogOut,
  User,
  X,
  Plus,
  List,
  ArrowBigUpDash,
  Play,
  Clock,
  Folder,
  Bell,
  BellOff,
  GitBranch,
  Dot,
} from "lucide-react";

export const Icons = {
  PENCIL: (props) => <Pencil {...props} />,
  PENCIL_LINE: (props) => <PencilLine {...props} />,
  CAN_SEE: (props) => <Eye {...props} size={props.size || 24} />,
  CANT_SEE: (props) => <EyeOff {...props} size={props.size || 24} />,
  CARET_DOWN: (props) => <ChevronDown {...props} />,
  CARET_UP: (props) => <ChevronUp {...props} />,
  CARET_LEFT: (props) => <ChevronLeft {...props} />,
  CARET_RIGHT: (props) => <ChevronRight {...props} />,
  QUESTION_CIRCLE: (props) => <MessageCircleQuestion size={20} {...props} />,
  CHECK: (props) => <Check {...props} />,
  EMAIL: (props) => <Mail {...props} />,
  TRASH: (props) => <Trash {...props} />,
  SIGN_OUT: (props) => <LogOut {...props} />,
  USER: (props) => <User {...props} />,
  THREE_DOTS_VERTICAL: (props) => <i className="ri-more-2-fill" {...props}></i>,
  THREE_DOTS_HORIZONTAL: (props) => <i className="ri-more-fill" {...props}></i>,
  X: (props) => <X {...props} />,
  PLUS: (props) => <Plus className="h-5 w-5" {...props} />,
  LIST: (props) => <List {...props} />,
  PUBLISH: (props) => <ArrowBigUpDash {...props} />,
  PLAY: (props) => <Play {...props} />,
  CLOCK: (props) => <Clock {...props} />,
  FOLDER: (props) => <Folder {...props} />,
  NOTIFICATION: (props) => <Bell {...props} />,
  NOTIFICATIONSLASH: (props) => <BellOff {...props} />,
  VERSION: (props) => <GitBranch {...props} />,
  DOT: (props) => <Dot {...props} />,
  SPINNER: (props) => <i class="ri-loader-4-line" {...props}></i>,
};
